// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package prompts

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC80ae7adDecodePodApiPkgPromts(in *jlexer.Lexer, out *Usage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "prompt_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PromptTokens = int(in.Int())
			}
		case "completion_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CompletionTokens = int(in.Int())
			}
		case "total_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalTokens = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodePodApiPkgPromts(out *jwriter.Writer, in Usage) {
	out.RawByte('{')
	first := true
	_ = first
	if in.PromptTokens != 0 {
		const prefix string = ",\"prompt_tokens\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.PromptTokens))
	}
	if in.CompletionTokens != 0 {
		const prefix string = ",\"completion_tokens\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.CompletionTokens))
	}
	if in.TotalTokens != 0 {
		const prefix string = ",\"total_tokens\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.TotalTokens))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Usage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodePodApiPkgPromts(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Usage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodePodApiPkgPromts(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Usage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodePodApiPkgPromts(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Usage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodePodApiPkgPromts(l, v)
}
func easyjsonC80ae7adDecodePodApiPkgPromts1(in *jlexer.Lexer, out *ToolSpec) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "function":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Function).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodePodApiPkgPromts1(out *jwriter.Writer, in ToolSpec) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"function\":"
		out.RawString(prefix)
		(in.Function).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ToolSpec) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodePodApiPkgPromts1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ToolSpec) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodePodApiPkgPromts1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ToolSpec) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodePodApiPkgPromts1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ToolSpec) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodePodApiPkgPromts1(l, v)
}
func easyjsonC80ae7adDecodePodApiPkgPromts2(in *jlexer.Lexer, out *ToolFunction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "arguments":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Arguments = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodePodApiPkgPromts2(out *jwriter.Writer, in ToolFunction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"arguments\":"
		out.RawString(prefix)
		out.String(string(in.Arguments))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ToolFunction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodePodApiPkgPromts2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ToolFunction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodePodApiPkgPromts2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ToolFunction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodePodApiPkgPromts2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ToolFunction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodePodApiPkgPromts2(l, v)
}
func easyjsonC80ae7adDecodePodApiPkgPromts3(in *jlexer.Lexer, out *ToolCall) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "function":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Function).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodePodApiPkgPromts3(out *jwriter.Writer, in ToolCall) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"function\":"
		out.RawString(prefix)
		(in.Function).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ToolCall) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodePodApiPkgPromts3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ToolCall) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodePodApiPkgPromts3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ToolCall) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodePodApiPkgPromts3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ToolCall) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodePodApiPkgPromts3(l, v)
}
func easyjsonC80ae7adDecodePodApiPkgPromts4(in *jlexer.Lexer, out *ResponseMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "role":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Role = Role(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "tool_calls":
			if in.IsNull() {
				in.Skip()
				out.ToolCalls = nil
			} else {
				in.Delim('[')
				if out.ToolCalls == nil {
					if !in.IsDelim(']') {
						out.ToolCalls = make([]ToolCall, 0, 1)
					} else {
						out.ToolCalls = []ToolCall{}
					}
				} else {
					out.ToolCalls = (out.ToolCalls)[:0]
				}
				for !in.IsDelim(']') {
					var v1 ToolCall
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.ToolCalls = append(out.ToolCalls, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "attachments":
			if m, ok := out.Attachments.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Attachments.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Attachments = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodePodApiPkgPromts4(out *jwriter.Writer, in ResponseMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix[1:])
		out.String(string(in.Role))
	}
	if in.Content != "" {
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	if len(in.ToolCalls) != 0 {
		const prefix string = ",\"tool_calls\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v2, v3 := range in.ToolCalls {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Attachments != nil {
		const prefix string = ",\"attachments\":"
		out.RawString(prefix)
		if m, ok := in.Attachments.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Attachments.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Attachments))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodePodApiPkgPromts4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodePodApiPkgPromts4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodePodApiPkgPromts4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodePodApiPkgPromts4(l, v)
}
func easyjsonC80ae7adDecodePodApiPkgPromts5(in *jlexer.Lexer, out *Prompt) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "messages":
			if in.IsNull() {
				in.Skip()
				out.Messages = nil
			} else {
				in.Delim('[')
				if out.Messages == nil {
					if !in.IsDelim(']') {
						out.Messages = make([]Message, 0, 0)
					} else {
						out.Messages = []Message{}
					}
				} else {
					out.Messages = (out.Messages)[:0]
				}
				for !in.IsDelim(']') {
					var v4 Message
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Messages = append(out.Messages, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "meta":
			if in.IsNull() {
				in.Skip()
				out.Meta = nil
			} else {
				if out.Meta == nil {
					out.Meta = new(Meta)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Meta).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodePodApiPkgPromts5(out *jwriter.Writer, in Prompt) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"messages\":"
		out.RawString(prefix)
		if in.Messages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Messages {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Meta != nil {
		const prefix string = ",\"meta\":"
		out.RawString(prefix)
		(*in.Meta).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Prompt) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodePodApiPkgPromts5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Prompt) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodePodApiPkgPromts5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Prompt) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodePodApiPkgPromts5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Prompt) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodePodApiPkgPromts5(l, v)
}
func easyjsonC80ae7adDecodePodApiPkgPromts6(in *jlexer.Lexer, out *Meta) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "tags":
			if in.IsNull() {
				in.Skip()
				out.Tags = nil
			} else {
				in.Delim('[')
				if out.Tags == nil {
					if !in.IsDelim(']') {
						out.Tags = make([]string, 0, 4)
					} else {
						out.Tags = []string{}
					}
				} else {
					out.Tags = (out.Tags)[:0]
				}
				for !in.IsDelim(']') {
					var v7 string
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = string(in.String())
					}
					out.Tags = append(out.Tags, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodePodApiPkgPromts6(out *jwriter.Writer, in Meta) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Title != "" {
		const prefix string = ",\"title\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	if len(in.Tags) != 0 {
		const prefix string = ",\"tags\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v8, v9 := range in.Tags {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Meta) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodePodApiPkgPromts6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Meta) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodePodApiPkgPromts6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Meta) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodePodApiPkgPromts6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Meta) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodePodApiPkgPromts6(l, v)
}
func easyjsonC80ae7adDecodePodApiPkgPromts7(in *jlexer.Lexer, out *Message) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "role":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Role = Role(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "content_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContentType = string(in.String())
			}
		case "tool_calls":
			if in.IsNull() {
				in.Skip()
				out.ToolCalls = nil
			} else {
				in.Delim('[')
				if out.ToolCalls == nil {
					if !in.IsDelim(']') {
						out.ToolCalls = make([]ToolCall, 0, 1)
					} else {
						out.ToolCalls = []ToolCall{}
					}
				} else {
					out.ToolCalls = (out.ToolCalls)[:0]
				}
				for !in.IsDelim(']') {
					var v10 ToolCall
					if in.IsNull() {
						in.Skip()
					} else {
						(v10).UnmarshalEasyJSON(in)
					}
					out.ToolCalls = append(out.ToolCalls, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "tool_call_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ToolCallID = string(in.String())
			}
		case "attachments":
			if m, ok := out.Attachments.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Attachments.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Attachments = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodePodApiPkgPromts7(out *jwriter.Writer, in Message) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix[1:])
		out.String(string(in.Role))
	}
	if in.Content != "" {
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	if in.Name != "" {
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	if in.ContentType != "" {
		const prefix string = ",\"content_type\":"
		out.RawString(prefix)
		out.String(string(in.ContentType))
	}
	if len(in.ToolCalls) != 0 {
		const prefix string = ",\"tool_calls\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v11, v12 := range in.ToolCalls {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.ToolCallID != "" {
		const prefix string = ",\"tool_call_id\":"
		out.RawString(prefix)
		out.String(string(in.ToolCallID))
	}
	if in.Attachments != nil {
		const prefix string = ",\"attachments\":"
		out.RawString(prefix)
		if m, ok := in.Attachments.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Attachments.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Attachments))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Message) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodePodApiPkgPromts7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Message) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodePodApiPkgPromts7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Message) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodePodApiPkgPromts7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Message) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodePodApiPkgPromts7(l, v)
}
func easyjsonC80ae7adDecodePodApiPkgPromts8(in *jlexer.Lexer, out *ChatResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "object":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Object = string(in.String())
			}
		case "created":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Created = int64(in.Int64())
			}
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "choices":
			if in.IsNull() {
				in.Skip()
				out.Choices = nil
			} else {
				in.Delim('[')
				if out.Choices == nil {
					if !in.IsDelim(']') {
						out.Choices = make([]ChatChoice, 0, 0)
					} else {
						out.Choices = []ChatChoice{}
					}
				} else {
					out.Choices = (out.Choices)[:0]
				}
				for !in.IsDelim(']') {
					var v13 ChatChoice
					if in.IsNull() {
						in.Skip()
					} else {
						(v13).UnmarshalEasyJSON(in)
					}
					out.Choices = append(out.Choices, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "usage":
			if in.IsNull() {
				in.Skip()
				out.Usage = nil
			} else {
				if out.Usage == nil {
					out.Usage = new(Usage)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Usage).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodePodApiPkgPromts8(out *jwriter.Writer, in ChatResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"object\":"
		out.RawString(prefix)
		out.String(string(in.Object))
	}
	{
		const prefix string = ",\"created\":"
		out.RawString(prefix)
		out.Int64(int64(in.Created))
	}
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix)
		out.String(string(in.Model))
	}
	{
		const prefix string = ",\"choices\":"
		out.RawString(prefix)
		if in.Choices == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Choices {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Usage != nil {
		const prefix string = ",\"usage\":"
		out.RawString(prefix)
		(*in.Usage).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChatResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodePodApiPkgPromts8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChatResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodePodApiPkgPromts8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChatResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodePodApiPkgPromts8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChatResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodePodApiPkgPromts8(l, v)
}
func easyjsonC80ae7adDecodePodApiPkgPromts9(in *jlexer.Lexer, out *ChatRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "messages":
			if in.IsNull() {
				in.Skip()
				out.Messages = nil
			} else {
				in.Delim('[')
				if out.Messages == nil {
					if !in.IsDelim(']') {
						out.Messages = make([]Message, 0, 0)
					} else {
						out.Messages = []Message{}
					}
				} else {
					out.Messages = (out.Messages)[:0]
				}
				for !in.IsDelim(']') {
					var v16 Message
					if in.IsNull() {
						in.Skip()
					} else {
						(v16).UnmarshalEasyJSON(in)
					}
					out.Messages = append(out.Messages, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "stream":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Stream = bool(in.Bool())
			}
		case "max_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxTokens = int(in.Int())
			}
		case "temperature":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Temperature = float32(in.Float32())
			}
		case "top_p":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopP = float32(in.Float32())
			}
		case "frequency_penalty":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FrequencyPenalty = float32(in.Float32())
			}
		case "presence_penalty":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PresencePenalty = float32(in.Float32())
			}
		case "tools":
			if in.IsNull() {
				in.Skip()
				out.Tools = nil
			} else {
				in.Delim('[')
				if out.Tools == nil {
					if !in.IsDelim(']') {
						out.Tools = make([]ToolSpec, 0, 1)
					} else {
						out.Tools = []ToolSpec{}
					}
				} else {
					out.Tools = (out.Tools)[:0]
				}
				for !in.IsDelim(']') {
					var v17 ToolSpec
					if in.IsNull() {
						in.Skip()
					} else {
						(v17).UnmarshalEasyJSON(in)
					}
					out.Tools = append(out.Tools, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodePodApiPkgPromts9(out *jwriter.Writer, in ChatRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix[1:])
		out.String(string(in.Model))
	}
	{
		const prefix string = ",\"messages\":"
		out.RawString(prefix)
		if in.Messages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.Messages {
				if v18 > 0 {
					out.RawByte(',')
				}
				(v19).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Stream {
		const prefix string = ",\"stream\":"
		out.RawString(prefix)
		out.Bool(bool(in.Stream))
	}
	if in.MaxTokens != 0 {
		const prefix string = ",\"max_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.MaxTokens))
	}
	if in.Temperature != 0 {
		const prefix string = ",\"temperature\":"
		out.RawString(prefix)
		out.Float32(float32(in.Temperature))
	}
	if in.TopP != 0 {
		const prefix string = ",\"top_p\":"
		out.RawString(prefix)
		out.Float32(float32(in.TopP))
	}
	if in.FrequencyPenalty != 0 {
		const prefix string = ",\"frequency_penalty\":"
		out.RawString(prefix)
		out.Float32(float32(in.FrequencyPenalty))
	}
	if in.PresencePenalty != 0 {
		const prefix string = ",\"presence_penalty\":"
		out.RawString(prefix)
		out.Float32(float32(in.PresencePenalty))
	}
	if len(in.Tools) != 0 {
		const prefix string = ",\"tools\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v20, v21 := range in.Tools {
				if v20 > 0 {
					out.RawByte(',')
				}
				(v21).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChatRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodePodApiPkgPromts9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChatRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodePodApiPkgPromts9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChatRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodePodApiPkgPromts9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChatRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodePodApiPkgPromts9(l, v)
}
func easyjsonC80ae7adDecodePodApiPkgPromts10(in *jlexer.Lexer, out *ChatChoice) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Index = int(in.Int())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Message).UnmarshalEasyJSON(in)
			}
		case "finish_reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FinishReason = string(in.String())
			}
		case "delta":
			if in.IsNull() {
				in.Skip()
				out.Delta = nil
			} else {
				if out.Delta == nil {
					out.Delta = new(ResponseMessage)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Delta).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodePodApiPkgPromts10(out *jwriter.Writer, in ChatChoice) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Index))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		(in.Message).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"finish_reason\":"
		out.RawString(prefix)
		out.String(string(in.FinishReason))
	}
	if in.Delta != nil {
		const prefix string = ",\"delta\":"
		out.RawString(prefix)
		(*in.Delta).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChatChoice) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodePodApiPkgPromts10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChatChoice) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodePodApiPkgPromts10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChatChoice) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodePodApiPkgPromts10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChatChoice) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodePodApiPkgPromts10(l, v)
}
