// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package apigen

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ChatImageRequest defines model for ChatImageRequest.
type ChatImageRequest struct {
	// Image Загруженное изображение (PNG/JPEG), содержащее текст
	Image openapi_types.File `json:"image"`

	// Text Промт пользователя
	Text *string `json:"text,omitempty"`
}

// CommonResponse Common response wrapper
type CommonResponse struct {
	Items []ResponseItem `json:"items"`
}

// ErrorResponse Error wrapper
type ErrorResponse struct {
	// Details Optional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error message
	Error string `json:"error"`
}

// ResponseItem defines model for ResponseItem.
type ResponseItem struct {
	CarouselImageUrls []string `json:"carouselImageUrls"`
	Description       string   `json:"description"`
	MainImageUrl      string   `json:"mainImageUrl"`
	Name              string   `json:"name"`
}

// TextRequest defines model for TextRequest.
type TextRequest struct {
	// Text Input text
	Text string `json:"text"`
}

// GetStaticImageParams defines parameters for GetStaticImage.
type GetStaticImageParams struct {
	// Callback URL для обратного вызова после скачивания
	Callback *string `form:"callback,omitempty" json:"callback,omitempty"`
}

// ChatImageMultipartRequestBody defines body for ChatImage for multipart/form-data ContentType.
type ChatImageMultipartRequestBody = ChatImageRequest

// RespondTextJSONRequestBody defines body for RespondText for application/json ContentType.
type RespondTextJSONRequestBody = TextRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Respond to an uploaded image containing text
	// (POST /api/v1/chat/image)
	ChatImage(ctx echo.Context) error
	// Respond to text input
	// (POST /api/v1/chat/text)
	RespondText(ctx echo.Context) error
	// Retrieve a generated or stored image
	// (GET /api/v1/images/{id})
	GetStaticImage(ctx echo.Context, id openapi_types.UUID, params GetStaticImageParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ChatImage converts echo context to params.
func (w *ServerInterfaceWrapper) ChatImage(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ChatImage(ctx)
	return err
}

// RespondText converts echo context to params.
func (w *ServerInterfaceWrapper) RespondText(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RespondText(ctx)
	return err
}

// GetStaticImage converts echo context to params.
func (w *ServerInterfaceWrapper) GetStaticImage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStaticImageParams
	// ------------- Optional query parameter "callback" -------------

	err = runtime.BindQueryParameter("form", true, false, "callback", ctx.QueryParams(), &params.Callback)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter callback: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStaticImage(ctx, id, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/v1/chat/image", wrapper.ChatImage)
	router.POST(baseURL+"/api/v1/chat/text", wrapper.RespondText)
	router.GET(baseURL+"/api/v1/images/:id", wrapper.GetStaticImage)

}

type ChatImageRequestObject struct {
	Body *multipart.Reader
}

type ChatImageResponseObject interface {
	VisitChatImageResponse(w http.ResponseWriter) error
}

type ChatImage200JSONResponse CommonResponse

func (response ChatImage200JSONResponse) VisitChatImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ChatImage400JSONResponse ErrorResponse

func (response ChatImage400JSONResponse) VisitChatImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ChatImage500JSONResponse ErrorResponse

func (response ChatImage500JSONResponse) VisitChatImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RespondTextRequestObject struct {
	Body *RespondTextJSONRequestBody
}

type RespondTextResponseObject interface {
	VisitRespondTextResponse(w http.ResponseWriter) error
}

type RespondText200JSONResponse CommonResponse

func (response RespondText200JSONResponse) VisitRespondTextResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RespondText400JSONResponse ErrorResponse

func (response RespondText400JSONResponse) VisitRespondTextResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RespondText500JSONResponse ErrorResponse

func (response RespondText500JSONResponse) VisitRespondTextResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetStaticImageRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params GetStaticImageParams
}

type GetStaticImageResponseObject interface {
	VisitGetStaticImageResponse(w http.ResponseWriter) error
}

type GetStaticImage200ImagejpegResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetStaticImage200ImagejpegResponse) VisitGetStaticImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/jpeg")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetStaticImage200ImagepngResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetStaticImage200ImagepngResponse) VisitGetStaticImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetStaticImage404JSONResponse ErrorResponse

func (response GetStaticImage404JSONResponse) VisitGetStaticImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetStaticImage500JSONResponse ErrorResponse

func (response GetStaticImage500JSONResponse) VisitGetStaticImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Respond to an uploaded image containing text
	// (POST /api/v1/chat/image)
	ChatImage(ctx context.Context, request ChatImageRequestObject) (ChatImageResponseObject, error)
	// Respond to text input
	// (POST /api/v1/chat/text)
	RespondText(ctx context.Context, request RespondTextRequestObject) (RespondTextResponseObject, error)
	// Retrieve a generated or stored image
	// (GET /api/v1/images/{id})
	GetStaticImage(ctx context.Context, request GetStaticImageRequestObject) (GetStaticImageResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ChatImage operation middleware
func (sh *strictHandler) ChatImage(ctx echo.Context) error {
	var request ChatImageRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ChatImage(ctx.Request().Context(), request.(ChatImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChatImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ChatImageResponseObject); ok {
		return validResponse.VisitChatImageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RespondText operation middleware
func (sh *strictHandler) RespondText(ctx echo.Context) error {
	var request RespondTextRequestObject

	var body RespondTextJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RespondText(ctx.Request().Context(), request.(RespondTextRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RespondText")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RespondTextResponseObject); ok {
		return validResponse.VisitRespondTextResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetStaticImage operation middleware
func (sh *strictHandler) GetStaticImage(ctx echo.Context, id openapi_types.UUID, params GetStaticImageParams) error {
	var request GetStaticImageRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetStaticImage(ctx.Request().Context(), request.(GetStaticImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStaticImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetStaticImageResponseObject); ok {
		return validResponse.VisitGetStaticImageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
